import app from './js/app';



import './css/reset.css';
import './css/pages/layout.css';
import './css/fonts.css';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/autoplay';
import 'swiper/css/effect-fade';
import 'swiper/css/grid';
import 'swiper/css/thumbs';
import 'swiper/css/virtual';
import './css/modules/header.css';
import './css/pages/index.css';
import './css/pages/product-card.css';
import './css/pages/catalog.css';
import './css/pages/brands.css';
import './css/pages/products-list.css';
import './css/pages/delivery.css';
import './css/pages/payment.css';
import './css/pages/about-us.css';
import './css/pages/contacts.css';
import './css/pages/requisites.css';
import './css/pages/favorites.css';
import './css/pages/basket.css';
import './css/pages/exchange-and-refund.css';
import './css/pages/404.css';
import './css/pages/loyalty-program.css';
import './css/components/component-nav-catalog.css';
import './css/components/component-burger.css';
import './css/components/component-nav-bar-mobile.css';
import './css/components/component-nav-mobile.css';
import './css/components/reviews.css';
import './css/components/pagination.css';
import './css/mixines/mixin-bread-crumbs.css';
import './css/mixines/mixin-catalog-card.css';
import './css/mixines/mixin-brand-card.css';
import './css/mixines/sku-card-list.css';
import './css/mixines/arrow-to-up.css';
import './css/mixines/label-input.css';
import './css/modules/footer.css';
import './css/effects.css';